apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: nodejs-feedback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image:  766025370940.dkr.ecr.ap-south-1.amazonaws.com/devops:v1
        imagePullPolicy: Always
        name: nodejs
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31300
  selector:
    app: webapp
  type: NodePort
                            
